//
// input recipe list from https://www.allrecipes.com/recipes/15103/salad/vegetable-salads/broccoli-salad
// In this array recipe titles are prefixed with a 0 and these are followed by ingredients, all of which
// are prefixed with a 1. So the first recipe is "Broccoli Coleslaw" which has ingredients "olive oil",
// "white vinegar",...,"sunflower seeds". The second recipe is "Creamy Broccoli Salad".
// The prefixes should not be printed out and can be stripped off the strings if that is convenient to you.
// The list ends with an empty string as terminator
//
char *rawRecipes[]={
"0Broccoli Coleslaw",
"1olive oil",
"1white vinegar",
"1white sugar",
"1package chicken flavored ramen noodles",
"1broccoli",
"1carrots",
"1green onions",
"1sunflower seeds",
"0Creamy Broccoli Salad",
"1broccoli",
"1red onion",
"1mozzarella cheese",
"1mayonnaise",
"1white sugar",
"1white wine vinegar",
"0Minnesota Broccoli Salad",
"1eggs",
"1broccoli",
"1red onion",
"1green olives",
"1pimentos",
"1mayonnaise",
"1dry mustard",
"1salt",
"1celery seed",
"1dill",
"0Curry Broccoli Salad",
"1broccoli",
"1diced onion",
"1dried cherries",
"1sunflower seeds",
"1mayonnaise",
"1curry powder",
"1cider vinegar",
"1white sugar",
"0Broccoli Buffet Salad",
"1broccoli",
"1red onion",
"1sunflower seeds",
"1raisins",
"1feta cheese",
"1yogurt",
"1mayonnaise",
"1white sugar",
"1lemon juice",
"1salt",
"1pepper",
"0Garlic Broccoli Salad",
"1broccoli",
"1olive oil",
"1pine nuts",
"1rice wine vinegar",
"1vegetable oil",
"1cloves garlic",
"1cayenne pepper",
"1raisins",
"0Alysons Broccoli Salad",
"1broccoli",
"1red onion",
"1raisins",
"1white wine vinegar",
"1white sugar",
"1mayonnaise",
"1sunflower seeds",
"0Broccoli and Ramen Noodle Salad",
"1broccoli coleslaw mix",
"1chicken flavored ramen noodles",
"1green onions",
"1peanuts",
"1sunflower seeds",
"1white sugar",
"1vegetable oil",
"1cider vinegar",
"0Zesty Broccoli and Cauliflower Salad",
"1broccoli",
"1cauliflower",
"1red onion",
"1Italian dressing",
"1sunflower seeds",
"0Mardis Broccoli Salad",
"1broccoli",
"1red onion",
"1jumbo black olives",
"1artichoke hearts",
"1tomatoes",
"1green onions",
"1Italian-style salad dressing",
"0Bops Broccoli Cauliflower Salad",
"1broccoli",
"1cauliflower",
"1Cheddar cheese",
"1red onion",
"1creamy salad dressing",
"1white sugar",
"1white vinegar",
"0Best Baconless Broccoli Salad",
"1broccoli",
"1red onion",
"1dried cranberries",
"1pumpkin seeds",
"1flax seeds",
"1mayonnaise",
"1raspberry vinegar",
"1white sugar",
"1pecans",
"0Broccoli Cauliflower Pepita Salad",
"1broccoli",
"1cauliflower",
"1red bell pepper",
"1onion",
"1pumpkin seeds",
"1mayonnaise",
"1yogurt",
"1red wine vinegar",
"1coconut palm sugar",
"1Dijon mustard",
"1salt",
"0Deli-Style Fresh Broccoli Salad",
"1broccoli",
"1green onion",
"1dried cranberries",
"1mayonnaise",
"1honey",
"1cider vinegar",
"0Broccoli Cauliflower Chickpea Bowl",
"1cashews",
"1broccoli",
"1cauliflower",
"1garlic powder",
"1salt",
"1black pepper",
"1chickpeas",
"1lemon juice",
"1tahini",
"1salt",
"0Broccoli Apple Cranberry Salad",
"1mayonnaise",
"1lemon juice",
"1agave nectar",
"1clove garlic",
"1apple cider vinegar",
"1black pepper",
"1sea salt",
"1broccoli",
"1apple",
"1almonds",
"1carrots",
"1red onion",
"1dried cranberries",
"0Broccoli Mango Salad",
"1ranch dressing",
"1orange juice",
"1horseradish",
"1broccoli",
"1mango",
"1cashews",
"1red onion",
"1mandarin oranges",
"0Asian Pasta Salad with Beef, Broccoli and Bean Sprouts",
"1garlic cloves",
"1soy sauce",
"1rice wine vinegar",
"1sugar",
"1sesame oil",
"1ground ginger",
"1hot red pepper flakes",
"1mayonnaise",
"1vegetable oil",
"1salt",
"1penne pasta",
"1broccoli",
"1carrots",
"1red bell pepper",
"1bean sprouts",
"1green onions",
"1peanuts",
"1cilantro",
"0Easy Broccoli Salad I",
"1broccoli",
"1red onion",
"1raisins",
"1sunflower seeds",
"1yogurt",
"1orange juice",
"1mayonnaise",
"0Minnesota Broccoli Salad",
"1eggs",
"1broccoli",
"1red onion",
"1green olives",
"1pimentos",
"1mayonnaise",
"1dry mustard",
"1salt",
"1celery seed",
"1dill",
"0Delicious Broccoli Cranberry Salad",
"1broccoli",
"1dried cranberries",
"1red onion",
"1chopped celery",
"1mayonnaise",
"1white sugar",
"1rice vinegar",
"1cashews",
"0Fruit and Broccoli Buffet Salad",
"1grapeseed oil",
"1granulated sugar",
"1cider vinegar",
"1lime juice",
"1lime zest",
"1garlic",
"1salt",
"1poppy seeds",
"1paprika",
"1dry mustard",
"1pecans",
"1oranges",
"1broccoli",
"1apple",
"1grapes",
"0Strawberry Broco-Flower Salad",
"1broccoli",
"1cauliflower",
"1carrot",
"1strawberries",
"1slivered almonds",
"1raspberry vinaigrette",
"0Broccoli and Tortellini Salad",
"1cheese-filled tortellini",
"1mayonnaise",
"1white sugar",
"1cider vinegar",
"1broccoli",
"1raisins",
"1sunflower seeds",
"1red onion",
""
};